name: Build and Push to Vercel Branch

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Build Documentation
        run: |
          pip install zensical
          zensical build --clean 
          
      - name: Deploy to Release Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: vercel-release
          force_orphan: true
